Admin.create(email: "admin@admin.com", password: "123456", name: "qqqq", phone: "oi", cpf: "aa")
Admin.first.manager!



#Materias Pre vestibular
@artes = Discipline.find_or_create_by(name: 'Artes', nick_name: 'Artes', discipline_type: 'pre_vestibular')
@bio = Discipline.find_or_create_by(name: 'Biologia', nick_name: 'Biologia', discipline_type: 'pre_vestibular')
@filo = Discipline.find_or_create_by(name: 'Filosofia', nick_name: 'Filosofia', discipline_type: 'pre_vestibular')
@fisica = Discipline.find_or_create_by(name: 'Física', nick_name: 'Física', discipline_type: 'pre_vestibular')
@geo = Discipline.find_or_create_by(name: 'Geografia', nick_name: 'Geografia', discipline_type: 'pre_vestibular')
@historia = Discipline.find_or_create_by(name: 'História', nick_name: 'História', discipline_type: 'pre_vestibular')
@mat = Discipline.find_or_create_by(name: 'Matemática', nick_name: 'Matemática', discipline_type: 'pre_vestibular')
@quimica = Discipline.find_or_create_by(name: 'Quimica', nick_name: 'Quimica', discipline_type: 'pre_vestibular')
@portugues = Discipline.find_or_create_by(name: 'Portugues', nick_name: 'Portugues', discipline_type: 'pre_vestibular')
@ingles = Discipline.find_or_create_by(name: 'Inglês', nick_name: 'Inglês', discipline_type: 'pre_vestibular')
@espanhol = Discipline.find_or_create_by(name: 'Espanhol', nick_name: 'Espanhol', discipline_type: 'pre_vestibular')

#Topicos Pre vestibular

#Artes
#Topic.find_or_create_by(name: 'Artes Cênicas', discipline_id: @artes.id)
#Topic.find_or_create_by(name: 'Artes Visuais', discipline_id: @artes.id)
#Topic.find_or_create_by(name: 'Musica', discipline_id: @artes.id)

#Biologia
#Topic.find_or_create_by(name: 'Moléculas, células', discipline_id: @bio.id)
#Topic.find_or_create_by(name: 'Hereditariedade e diversidade de vida', discipline_id: @bio.id)
#Topic.find_or_create_by(name: 'Identidade dos seres vivos', discipline_id: @bio.id)
#Topic.find_or_create_by(name: 'Hereditariedade e diversidade de vida', discipline_id: @bio.id)
#Topic.find_or_create_by(name: 'Ecologia e ciências ambientais', discipline_id: @bio.id)
#Topic.find_or_create_by(name: 'Zoologia', discipline_id: @bio.id)
#Topic.find_or_create_by(name: 'Botânica', discipline_id: @bio.id)
#Topic.find_or_create_by(name: 'Origem e evolução da vida', discipline_id: @bio.id)
#Topic.find_or_create_by(name: 'Qualidade de vida da população humana', discipline_id: @bio.id)

#Filosofia
#Topic.find_or_create_by(name: 'O que é a Filosofia', discipline_id: @filo.id)
#Topic.find_or_create_by(name: 'Filosofia e a Grecia Antiga', discipline_id: @filo.id)
#Topic.find_or_create_by(name: 'Conceitos Filosoficos', discipline_id: @filo.id)
#Topic.find_or_create_by(name: 'O Sujeito Moderno', discipline_id: @filo.id)
#Topic.find_or_create_by(name: 'Maquiavel e o principe', discipline_id: @filo.id)
#Topic.find_or_create_by(name: 'A Politica Grega(Platão e Aristoteles', discipline_id: @filo.id)
#Topic.find_or_create_by(name: 'Pensamentos Politicos - Karl Marx', discipline_id: @filo.id)
#Topic.find_or_create_by(name: 'Pensamentos Politicos - Liberalismo', discipline_id: @filo.id)

#Fisica
#Topic.find_or_create_by(name: 'Cinemática', discipline_id: @fisica.id)
#Topic.find_or_create_by(name: 'Dinâmica', discipline_id: @fisica.id)
#Topic.find_or_create_by(name: 'Gravitação Universal', discipline_id: @fisica.id)
#Topic.find_or_create_by(name: 'Estática e Hidrost', discipline_id: @fisica.id)
#Topic.find_or_create_by(name: 'Física Térmica - Termologia', discipline_id: @fisica.id)
#Topic.find_or_create_by(name: 'Oscilação e Ondas', discipline_id: @fisica.id)
#Topic.find_or_create_by(name: 'Otica', discipline_id: @fisica.id)
#Topic.find_or_create_by(name: 'Eletricidade', discipline_id: @fisica.id)
#Topic.find_or_create_by(name: 'Magnetismo', discipline_id: @fisica.id)
#Topic.find_or_create_by(name: 'Fisica Moderna', discipline_id: @fisica.id)

#Geografia
#Topic.find_or_create_by(name: 'Cartografia', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Geologia', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Geografia Física', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Agropecuárea', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'População', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Urbanização', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Industrialização', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Energia', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Meio Ambiente', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Amazônia', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Integração Regional', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Globalização', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Desenvolvimento', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Historia da Geografia', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Geografia Cultural', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Geografia Econômica', discipline_id: @geo.id)
#Topic.find_or_create_by(name: 'Geografia Política', discipline_id: @geo.id)

#Historia
#Topic.find_or_create_by(name: 'Pré História', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Antiguidade Oriental(Egípcios, Mesopotâmicos, Persas...)', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Antiguidade Ocidental(Gregos, Romanos, Macedônios)', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Medievalidade Europeia', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Mundo Árabe', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Renascimento Ciêntifico', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Movimentos de Reforma Religiosa', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Mercantilismo', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Espanção Comercial a Marítima', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Colonialismo', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Iluminismo', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Revolução Industrial', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Absolutismo', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Independencia das 13 colônias', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Revolução Francesa', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Independencia das colônias latino-americanas', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Revoluções Liberais na Europa', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Imperialismo e Colonialismo século XIX', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Primeira Guerra Mundial', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Periodo Entre-Guerra: Revolução Russa de 1917', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Periodo Entre-Guerra: Crise de 1929', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Periodo Entre-Guerra: Totalitarismo', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Segunda Guerra Mundial', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Guerra Fria', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Revolução Chinesa', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Pré História Brasileira', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Colonialismo e ocupação Portuguesa no Brasil', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Periodo Colonial', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Processo de Independência', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Brasil Monarquico: Primeiro Reinado', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Brasil Monarquico: Segundo Reinado', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Republica Oligárquica', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Era Vargas', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Republica de 1954 a 1964', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Republica Autoritária', discipline_id: @historia.id)
#Topic.find_or_create_by(name: 'Historia da América latina', discipline_id: @historia.id)

#Matematica
#Topic.find_or_create_by(name: 'Aritmética e Problemas', discipline_id: @mat.id)
#Topic.find_or_create_by(name: 'Álgebra', discipline_id: @mat.id)
#Topic.find_or_create_by(name: 'Funções', discipline_id: @mat.id)
#Topic.find_or_create_by(name: 'Logarítimo', discipline_id: @mat.id)
#Topic.find_or_create_by(name: 'Progreção', discipline_id: @mat.id)
#Topic.find_or_create_by(name: 'Trigonometria', discipline_id: @mat.id)
#Topic.find_or_create_by(name: 'Análise Combinatória', discipline_id: @mat.id)
#Topic.find_or_create_by(name: 'Probabilidade', discipline_id: @mat.id)
#Topic.find_or_create_by(name: 'Binômio de Newton', discipline_id: @mat.id)
#Topic.find_or_create_by(name: 'Geometria Plana', discipline_id: @mat.id)
#Topic.find_or_create_by(name: 'Geometria Analítica', discipline_id: @mat.id)
#Topic.find_or_create_by(name: 'Geometria Espacial', discipline_id: @mat.id)
#Topic.find_or_create_by(name: 'Números Complexos', discipline_id: @mat.id)
#Topic.find_or_create_by(name: 'Polinômios', discipline_id: @mat.id)
#Topic.find_or_create_by(name: 'Estatistica', discipline_id: @mat.id)

#Quimica
#Topic.find_or_create_by(name: 'Transformações Químicas', discipline_id: @quimica.id)
#Topic.find_or_create_by(name: 'Cinética Quimica', discipline_id: @quimica.id)
#Topic.find_or_create_by(name: 'Equilíbrio Quimico', discipline_id: @quimica.id)
#Topic.find_or_create_by(name: 'Quimica Orgânica', discipline_id: @quimica.id)
#Topic.find_or_create_by(name: 'Energias Quimicas no Cotidiano', discipline_id: @quimica.id)
#Topic.find_or_create_by(name: 'Estequiometria', discipline_id: @quimica.id)
#Topic.find_or_create_by(name: 'Pilha e Hidrólise', discipline_id: @quimica.id)

#Portugues
#Topic.find_or_create_by(name: 'Fonologia', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'Ortografia', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'Morfologia', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'Verbos', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'Pronomes', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'Sintaxe', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'pontuação', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'Funções morfosintaxe da palavra: SE', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'Funções morfosintaxe da palavra: QUE', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'Funções morfosintaxe da palavra: COMO', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'Funções morfosintaxe da palavra: ATÉ', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'Funções morfosintaxe da palavra: SÓ', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'Funções morfosintaxe da palavra: MESMO', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'Crase', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'Problemas da Lingua Culta', discipline_id: @portugues.id)
#Topic.find_or_create_by(name: 'Interpretação de texto', discipline_id: @portugues.id)

#Ingles
#Topic.find_or_create_by(name: 'Adjetivos', discipline_id: @ingles.id)
#Topic.find_or_create_by(name: 'Números', discipline_id: @ingles.id)
#Topic.find_or_create_by(name: 'Preposições', discipline_id: @ingles.id)
#Topic.find_or_create_by(name: 'Pronomes', discipline_id: @ingles.id)
#Topic.find_or_create_by(name: 'Adjetivos', discipline_id: @ingles.id)
#Topic.find_or_create_by(name: 'Interpretação de Texto(Ingles)', discipline_id: @ingles.id)
#Topic.find_or_create_by(name: 'Vocabulário', discipline_id: @ingles.id)
#Topic.find_or_create_by(name: 'Verbo', discipline_id: @ingles.id)
#Topic.find_or_create_by(name: 'Sintaxe', discipline_id: @ingles.id)

#Espanhol
#Topic.find_or_create_by(name: 'Adjetivos', discipline_id: @espanhol.id)
#Topic.find_or_create_by(name: 'Números', discipline_id: @espanhol.id)
#Topic.find_or_create_by(name: 'Preposições', discipline_id: @espanhol.id)
#Topic.find_or_create_by(name: 'Pronomes', discipline_id: @espanhol.id)
#Topic.find_or_create_by(name: 'Adjetivos', discipline_id: @espanhol.id)
#Topic.find_or_create_by(name: 'Interpretação de Texto(espanhol)', discipline_id: @espanhol.id)
#Topic.find_or_create_by(name: 'Vocabulário', discipline_id: @espanhol.id)
#Topic.find_or_create_by(name: 'Verbo', discipline_id: @espanhol.id)
#Topic.find_or_create_by(name: 'Sintaxe', discipline_id: @espanhol.id)



#Materias Para concurço
Discipline.find_or_create_by(name: 'Português', nick_name: 'Português', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Constitucional', nick_name: 'D. Const', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Administrativo', nick_name: 'D. Admin', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Penal', nick_name: 'D. Penal', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Raciocínio Lógico', nick_name: 'R. Lógico', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Noções de Informática', nick_name: 'N. Informática', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Matemática', nick_name: 'Matemática', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Processual Civil - CPC 2015', nick_name: 'CPC 2015', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Civil', nick_name: 'D. Civil', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Processual Penal', nick_name: 'DP Penal', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Estatuto da Pessoa com Deficiência', nick_name: 'EP Deficiência', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Administração Geral', nick_name: 'Adm Geral', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito do Trabalho', nick_name: 'D. Trabalho', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Legislação Estadual', nick_name: 'L. Estadual', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Administração Pública', nick_name: 'Adm Pública', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Redação Oficial', nick_name: 'Red Oficial', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Legislação Federal', nick_name: 'L. Federal', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direitos Humanos', nick_name: 'D. Humanos', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Atualidades', nick_name: 'Atualidades', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'História', nick_name: 'História', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Ética na Administração Pública', nick_name: 'E. Adm Publica', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Tributário', nick_name: 'D. Tribut', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Gestão de Pessoas', nick_name: 'G. Pessoas', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Eleitoral', nick_name: 'D. Eleitoral', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Regimento Interno', nick_name: 'R. Interno', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Administração Fin e Orçamentária', nick_name: 'Adm Fin', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Arquivologia', nick_name: 'Arquivologia', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito da Criança e do Adolescente - ECA', nick_name: 'ECA', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Processual do Trabalho', nick_name: 'DP Trabalho', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Empresarial (Comercial)', nick_name: 'D. Emp', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Ambiental', nick_name: 'D. Ambiental', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Previdenciário', nick_name: 'D. Prev', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Contabilidade Geral', nick_name: 'C. Geral', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Administração de Recursos Materiais', nick_name: 'A. R. Materiais', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Inglês', nick_name: 'Inglês', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Legislação dos Tribunais de Justiça (TJs)', nick_name: 'L. TJ', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito do Consumidor', nick_name: 'D. Consumidor', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Legislação de Trânsito', nick_name: 'L. Trânsito', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Penal Militar', nick_name: 'DP Militar', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Legislação dos TRFs, STJ, STF e CNJ', nick_name: 'L. TRFs, STJ, STF, CNJ', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Matemática Financeira', nick_name: 'M. Fin', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Segurança e Saúde no Trabalho', nick_name: 'S. Trab', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Sociologia', nick_name: 'Sociologia', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Estatuto da Advocacia e da OAB', nick_name: 'OAB', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Legislação do Ministério Público', nick_name: 'LM Público', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Internacional Público', nick_name: 'DI. Público', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Gerência de Projetos', nick_name: 'G. Proj', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Redes de Computadores', nick_name: 'Redes', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Contabilidade Pública', nick_name: 'C. Pub', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Financeiro', nick_name: 'D. Financeiro', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Estatuto do Idoso', nick_name: 'E. Idoso', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Noções de Primeiros Socorros', nick_name: 'N. P. Socorros', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Serviço Social', nick_name: 'S. Social', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Atendimento ao Público', nick_name: 'At Pub', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Banco de Dados', nick_name: 'BD', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Segurança da Informação', nick_name: 'Seg Info', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Legislação dos Tribunais do Trabalho', nick_name: 'TST, TRTs', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Processual Penal Militar', nick_name: 'DPP Militar', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Sistemas Operacionais', nick_name: 'S. Operacionais', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Contabilidade de Custos', nick_name: 'C. Custos', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Economia', nick_name: 'Economia', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Espanhol', nick_name: 'Espanhol', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Internacional Privado', nick_name: 'DI Privado', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Criminologia', nick_name: 'Criminologia', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Estatística', nick_name: 'Estatística', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Auditoria', nick_name: 'Auditoria', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Legislação da Defensoria Pública', nick_name: 'LD Pública', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Controle Externo', nick_name: 'C. Externo', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Meio Ambiente', nick_name: 'M. Ambiente', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Segurança e Transporte', nick_name: 'S. Transporte', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Relações Humanas', nick_name: 'R. Humanas', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Farmácia', nick_name: 'Farmácia', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Segurança Pública', nick_name: 'S Pública', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Biblioteconomia', nick_name: 'Biblioteconomia', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Conhecimentos Bancários', nick_name: 'C. Bancários', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Segurança', nick_name: 'Segurança', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Econômico', nick_name: 'D Econômico', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Análise de Balanços', nick_name: 'A. Balanços', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Criminalística', nick_name: 'Criminalística', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Medicina do Trabalho', nick_name: 'M. Trabalho', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Metodologia da Investigação Policial', nick_name: 'MI Policial', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Legislação da AGU', nick_name: 'AGU', discipline_type: 'preparatorio_concurcos')
Discipline.find_or_create_by(name: 'Direito Marítimo', nick_name: 'D. Marítimo', discipline_type: 'preparatorio_concurcos')



