Admin.create(email: "admin@admin.com", password: "123456", name: "qqqq", phone: "oi", cpf: "aa")
Admin.first.manager!



#Materias
@artes = Discipline.find_or_create_by(name: 'Artes')
@bio = Discipline.find_or_create_by(name: 'Biologia')
@filo = Discipline.find_or_create_by(name: 'Filosofia')
@fisica = Discipline.find_or_create_by(name: 'Física')
@geo = Discipline.find_or_create_by(name: 'Geografia')
@historia = Discipline.find_or_create_by(name: 'História')
@mat = Discipline.find_or_create_by(name: 'Matematica')
@quimica = Discipline.find_or_create_by(name: 'Quimica')
@portugues = Discipline.find_or_create_by(name: 'portugues')
@ingles = Discipline.find_or_create_by(name: 'ingles')
@espanhol = Discipline.find_or_create_by(name: 'Espanhol')

#Topicos

#Artes
Topic.find_or_create_by(name: 'Artes Cênicas', discipline_id: @artes.id)
Topic.find_or_create_by(name: 'Artes Visuais', discipline_id: @artes.id)
Topic.find_or_create_by(name: 'Musica', discipline_id: @artes.id)

#Biologia
Topic.find_or_create_by(name: 'Moléculas, células', discipline_id: @bio.id)
Topic.find_or_create_by(name: 'Hereditariedade e diversidade de vida', discipline_id: @bio.id)
Topic.find_or_create_by(name: 'Identidade dos seres vivos', discipline_id: @bio.id)
Topic.find_or_create_by(name: 'Hereditariedade e diversidade de vida', discipline_id: @bio.id)
Topic.find_or_create_by(name: 'Ecologia e ciências ambientais', discipline_id: @bio.id)
Topic.find_or_create_by(name: 'Zoologia', discipline_id: @bio.id)
Topic.find_or_create_by(name: 'Botânica', discipline_id: @bio.id)
Topic.find_or_create_by(name: 'Origem e evolução da vida', discipline_id: @bio.id)
Topic.find_or_create_by(name: 'Qualidade de vida da população humana', discipline_id: @bio.id)

#Filosofia
Topic.find_or_create_by(name: 'O que é a Filosofia', discipline_id: @filo.id)
Topic.find_or_create_by(name: 'Filosofia e a Grecia Antiga', discipline_id: @filo.id)
Topic.find_or_create_by(name: 'Conceitos Filosoficos', discipline_id: @filo.id)
Topic.find_or_create_by(name: 'O Sujeito Moderno', discipline_id: @filo.id)
Topic.find_or_create_by(name: 'Maquiavel e o principe', discipline_id: @filo.id)
Topic.find_or_create_by(name: 'A Politica Grega(Platão e Aristoteles', discipline_id: @filo.id)
Topic.find_or_create_by(name: 'Pensamentos Politicos - Karl Marx', discipline_id: @filo.id)
Topic.find_or_create_by(name: 'Pensamentos Politicos - Liberalismo', discipline_id: @filo.id)

#Fisica
Topic.find_or_create_by(name: 'Cinemática', discipline_id: @fisica.id)
Topic.find_or_create_by(name: 'Dinâmica', discipline_id: @fisica.id)
Topic.find_or_create_by(name: 'Gravitação Universal', discipline_id: @fisica.id)
Topic.find_or_create_by(name: 'Estática e Hidrost', discipline_id: @fisica.id)
Topic.find_or_create_by(name: 'Física Térmica - Termologia', discipline_id: @fisica.id)
Topic.find_or_create_by(name: 'Oscilação e Ondas', discipline_id: @fisica.id)
Topic.find_or_create_by(name: 'Otica', discipline_id: @fisica.id)
Topic.find_or_create_by(name: 'Eletricidade', discipline_id: @fisica.id)
Topic.find_or_create_by(name: 'Magnetismo', discipline_id: @fisica.id)
Topic.find_or_create_by(name: 'Fisica Moderna', discipline_id: @fisica.id)

#Geografia
Topic.find_or_create_by(name: 'Cartografia', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Geologia', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Geografia Física', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Agropecuárea', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'População', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Urbanização', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Industrialização', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Energia', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Meio Ambiente', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Amazônia', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Integração Regional', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Globalização', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Desenvolvimento', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Historia da Geografia', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Geografia Cultural', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Geografia Econômica', discipline_id: @geo.id)
Topic.find_or_create_by(name: 'Geografia Política', discipline_id: @geo.id)

#Historia
Topic.find_or_create_by(name: 'Pré História', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Antiguidade Oriental(Egípcios, Mesopotâmicos, Persas...)', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Antiguidade Ocidental(Gregos, Romanos, Macedônios)', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Medievalidade Europeia', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Mundo Árabe', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Renascimento Ciêntifico', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Movimentos de Reforma Religiosa', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Mercantilismo', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Espanção Comercial a Marítima', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Colonialismo', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Iluminismo', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Revolução Industrial', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Absolutismo', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Independencia das 13 colônias', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Revolução Francesa', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Independencia das colônias latino-americanas', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Revoluções Liberais na Europa', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Imperialismo e Colonialismo século XIX', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Primeira Guerra Mundial', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Periodo Entre-Guerra: Revolução Russa de 1917', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Periodo Entre-Guerra: Crise de 1929', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Periodo Entre-Guerra: Totalitarismo', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Segunda Guerra Mundial', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Guerra Fria', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Revolução Chinesa', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Pré História Brasileira', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Colonialismo e ocupação Portuguesa no Brasil', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Periodo Colonial', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Processo de Independência', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Brasil Monarquico: Primeiro Reinado', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Brasil Monarquico: Segundo Reinado', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Republica Oligárquica', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Era Vargas', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Republica de 1954 a 1964', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Republica Autoritária', discipline_id: @historia.id)
Topic.find_or_create_by(name: 'Historia da América latina', discipline_id: @historia.id)

#Matematica
Topic.find_or_create_by(name: 'Aritmética e Problemas', discipline_id: @mat.id)
Topic.find_or_create_by(name: 'Álgebra', discipline_id: @mat.id)
Topic.find_or_create_by(name: 'Funções', discipline_id: @mat.id)
Topic.find_or_create_by(name: 'Logarítimo', discipline_id: @mat.id)
Topic.find_or_create_by(name: 'Progreção', discipline_id: @mat.id)
Topic.find_or_create_by(name: 'Trigonometria', discipline_id: @mat.id)
Topic.find_or_create_by(name: 'Análise Combinatória', discipline_id: @mat.id)
Topic.find_or_create_by(name: 'Probabilidade', discipline_id: @mat.id)
Topic.find_or_create_by(name: 'Binômio de Newton', discipline_id: @mat.id)
Topic.find_or_create_by(name: 'Geometria Plana', discipline_id: @mat.id)
Topic.find_or_create_by(name: 'Geometria Analítica', discipline_id: @mat.id)
Topic.find_or_create_by(name: 'Geometria Espacial', discipline_id: @mat.id)
Topic.find_or_create_by(name: 'Números Complexos', discipline_id: @mat.id)
Topic.find_or_create_by(name: 'Polinômios', discipline_id: @mat.id)
Topic.find_or_create_by(name: 'Estatistica', discipline_id: @mat.id)

#Quimica
Topic.find_or_create_by(name: 'Transformações Químicas', discipline_id: @quimica.id)
Topic.find_or_create_by(name: 'Cinética Quimica', discipline_id: @quimica.id)
Topic.find_or_create_by(name: 'Equilíbrio Quimico', discipline_id: @quimica.id)
Topic.find_or_create_by(name: 'Quimica Orgânica', discipline_id: @quimica.id)
Topic.find_or_create_by(name: 'Energias Quimicas no Cotidiano', discipline_id: @quimica.id)
Topic.find_or_create_by(name: 'Estequiometria', discipline_id: @quimica.id)
Topic.find_or_create_by(name: 'Pilha e Hidrólise', discipline_id: @quimica.id)

#Portugues
Topic.find_or_create_by(name: 'Fonologia', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'Ortografia', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'Morfologia', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'Verbos', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'Pronomes', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'Sintaxe', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'pontuação', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'Funções morfosintaxe da palavra: SE', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'Funções morfosintaxe da palavra: QUE', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'Funções morfosintaxe da palavra: COMO', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'Funções morfosintaxe da palavra: ATÉ', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'Funções morfosintaxe da palavra: SÓ', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'Funções morfosintaxe da palavra: MESMO', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'Crase', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'Problemas da Lingua Culta', discipline_id: @portugues.id)
Topic.find_or_create_by(name: 'Interpretação de texto', discipline_id: @portugues.id)

#Ingles
Topic.find_or_create_by(name: 'Adjetivos', discipline_id: @ingles.id)
Topic.find_or_create_by(name: 'Números', discipline_id: @ingles.id)
Topic.find_or_create_by(name: 'Preposições', discipline_id: @ingles.id)
Topic.find_or_create_by(name: 'Pronomes', discipline_id: @ingles.id)
Topic.find_or_create_by(name: 'Adjetivos', discipline_id: @ingles.id)
Topic.find_or_create_by(name: 'Interpretação de Texto(Ingles)', discipline_id: @ingles.id)
Topic.find_or_create_by(name: 'Vocabulário', discipline_id: @ingles.id)
Topic.find_or_create_by(name: 'Verbo', discipline_id: @ingles.id)
Topic.find_or_create_by(name: 'Sintaxe', discipline_id: @ingles.id)

#Espanhol
Topic.find_or_create_by(name: 'Adjetivos', discipline_id: @espanhol.id)
Topic.find_or_create_by(name: 'Números', discipline_id: @espanhol.id)
Topic.find_or_create_by(name: 'Preposições', discipline_id: @espanhol.id)
Topic.find_or_create_by(name: 'Pronomes', discipline_id: @espanhol.id)
Topic.find_or_create_by(name: 'Adjetivos', discipline_id: @espanhol.id)
Topic.find_or_create_by(name: 'Interpretação de Texto(espanhol)', discipline_id: @espanhol.id)
Topic.find_or_create_by(name: 'Vocabulário', discipline_id: @espanhol.id)
Topic.find_or_create_by(name: 'Verbo', discipline_id: @espanhol.id)
Topic.find_or_create_by(name: 'Sintaxe', discipline_id: @espanhol.id)
